---
title: "R Notebook"
output: html_notebook
---



```{r}

library(tidyverse)
library(cluster)
library(factoextra)
library(dendextend)
library(broom)

```

```{r}

computers_raw <- read_csv("data/computers.csv")

```


```{r}

summary(computers_raw)

```


```{r}

ggplot(computers_raw) +
  aes(x = ram, y = hd) +
  geom_point()



```


An initial look at the data shows that it may be suitable for clustering, let's scale it then look again



```{r}

computers_scale <- computers_raw %>%
  mutate_if(is.numeric, scale)


```


```{r}

ggplot(computers_scale) +
  aes(x = ram, y = hd) +
  geom_point()


```


better, there appears initially to be 4, potentially 5 clusters, 3/4 columns on the left and a larger spaced cluster to the top right. 


```{r}

computers_scale <- computers_scale %>%
  select(ram, hd)


```


```{r}

fviz_nbclust(computers_scale, kmeans, method = "wss", nstart = 25)

```


```{r}

fviz_nbclust(computers_scale, kmeans, method = "silhouette", nstart = 25)


```


```{r}

fviz_nbclust(computers_scale, kmeans, method = "gap_stat")


```


```{r}

clustered_computers <- kmeans(computers_scale, 2, nstart =2)


```


```{r}

clusters <- augment(clustered_computers, computers_raw)


```


```{r}

ggplot(clusters, aes(x = hd, y = ram, colour = .cluster)) +
  geom_point()


```


```{r}
```


```{r}
```


```{r}
```


```{r}
```



