---
title: "Manual model development"
output: html_notebook
---

```{r}

library(tidyverse)
library(ggiraphExtra)
library(GGally)



```


```{r}

housing_raw <- read_csv("data/kc_house_data.csv")


```


```{r}

glimpse(housing_raw)


```


```{r}

summary(housing_raw)


```


```{r}

unique(housing_raw$waterfront)

```


```{r}

housing_tidy <- housing_raw %>%
  select(-c(date, id, sqft_living15, sqft_lot15, zipcode)) %>%
  mutate(waterfront = as.logical(waterfront))

summary(housing_tidy)

```


```{r}


unique(housing_tidy$view)
# could make dummy variables for these as we don't know if the effect of multiple views is additative

```


```{r}

unique(housing_tidy$condition)
unique(housing_tidy$grade)
# both seem categorical; they're both ratings that are ordinal but not actual intervals

```


```{r}

alias(price ~ ., data = housing_tidy)


```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


