---
title: "R Notebook"
output: html_notebook
---

```{r}

library(janitor)
library(infer)
library(tidyverse)

```


```{r}

ames_data <- read_csv("data/ames.csv")

```


```{r}

ames_data <- clean_names(ames_data)

```

```{r}

ames_data %>%
  select(lot_area) %>%
  ggplot() +
  aes(x=lot_area) +
  geom_histogram(bins = 200, col = "white")


```


looks kind of normal with a positive skewed distribution


```{r}


bootstrap_ame <- ames_data %>%
  specify(response = lot_area) %>%
  generate(reps = 10000, type = "bootstrap") %>%
  calculate(stat = "mean") 


```


```{r}
bootstrap_ame %>%
  visualise(bins = 30)
  
  
  
```


```{r}

ci_95_ame <- bootstrap_ame %>%
  get_ci(level = 0.95, type = "percentile")

ci_95_ame



```


```{r}

bootstrap_ame %>%
  visualise(bins = 30) +
  shade_ci(endpoints = ci_95_ame)

```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```




















